In [1]:
import numpy as np

In [4]:
oneD= np.array([0,1,2,3])

In [5]:
twoD= np.array([[0,1,2],[3,4,5]])
twoD

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
one = np.arange(20).reshape(4,5)
two = np.arange(40,60).reshape(4,5)

In [15]:
np.hstack([one,two])
np.vstack([one,two])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

# Broadcasting

In [21]:
one / two
# one ** two

array([[0.        , 0.02439024, 0.04761905, 0.06976744, 0.09090909],
       [0.11111111, 0.13043478, 0.14893617, 0.16666667, 0.18367347],
       [0.2       , 0.21568627, 0.23076923, 0.24528302, 0.25925926],
       [0.27272727, 0.28571429, 0.29824561, 0.31034483, 0.3220339 ]])

In [22]:
np.std(one) ## Standard deviation

5.766281297335398